http:
  port: "8081"
  
sfdc:
  username: "shravan.chidurala@apisero.com"
  password: "Saanvi@23"
  token: "XaX2ccVlaSJXRnmcjQJtCgNn1"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"
  
file:
  accountsDir: "C:/Users/USER/Desktop/Mule4-MCD/APDevFundamentals4.3_studentFiles_SP_31aug2020/APDevFundamentals4.3_studentFiles_SP_31aug2020/resources"